#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="Hack Nerd Font"
ICON_FONT="SF Pro"
PADDINGS=3

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper 2>/dev/null
(cd $CONFIG_DIR/helper && make 2>/dev/null)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Bar appearance
bar=(
  height=36
  color=$BAR_COLOR
  border_width=1
  border_color=$BAR_BORDER_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=20
  padding_left=20
  y_offset=8
  margin=20
  corner_radius=12
  topmost=window
  notch_width=200
  notch_offset=0
)
sketchybar --bar "${bar[@]}"

# Defaults
defaults=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:17.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Regular:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)
sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --hotload on
sketchybar --update

echo "sketchybar configuration loaded.."
